@startuml
actor User
participant ":UI" as UI
participant ":Parser" as Parser
participant ":AddIncomeCommand" as AddIncomeCommand

User -> UI : "add category/Salary amt/2500.00 d/01-01-2024"
activate UI

UI -> Parser : getCommandFromInput("add category/Salary amt/2500.00 d/01-01-2024")
activate Parser

Parser -> Parser : Check if input starts with "add category/"
Parser --> UI : return AddIncomeCommand(input)
UI --> User : display result
deactivate Parser
deactivate UI

@enduml