@startuml

hide circle
skinparam classAttributeIconSize 0

package budgetflow.command {
    class DeleteExpenseCommand {
        # String input
        # CommandType commandType
        # String outputMessage
        + DeleteExpenseCommand(String input)
        + execute(List<Income> incomes, ExpenseList expenseList) throws UnfoundExpenseException
    }
}

package budgetflow.expense {
    class ExpenseList {
        + int getSize()
        + Expense get(int index)
        + void delete(int index)
        + double getAmount()
    }
}

class budgetflow.income.Income {

}


class budgetflow.exception.InvalidNumberFormatException {
    + InvalidNumberFormatException(String message)
}

abstract class "{abstract} \n Command" {
    + CommandType: commandType
    + Command(String input)
}


DeleteExpenseCommand --|> "{abstract} \n Command" : extends
DeleteExpenseCommand --> ExpenseList : uses
DeleteExpenseCommand --> Income : uses
DeleteExpenseCommand --> InvalidNumberFormatException : throws
@enduml
