@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
package budgetflow.expense {
    class Expense {
        -description: String
        -amount: double
        -date: String
        -category: String
        +Expense()
        +Expense(...)
    }
    class ExpenseList {
        -totalExpenses: double
        +ExpenseList()
        +ExpenseList(...)
        +delete(int)
        +getByTag(...): ExpenseList
        +getTotalExpense()
        +updateTotalExpense()
    }
}
ExpenseList "1" *-- "0..*" Expense :  innerList
@enduml