@startuml
'https://plantuml.com/sequence-diagram

participant ":FindExpenseCommand" as command
participant "expenseList: ExpenseList" as expenseList
-> command ++: execute()
command -> command ++: extract tag and keyword
command --> command --: tag, keyword
command -> expenseList ++: get expenses based on tag and keyword
command <-- expenseList --: matching expenses
command -> command ++: get number of matching expenses
command --> command --: number of matching expenses
alt no matching expenses
    <-- command: unfound expense exception
else number of matching expenses > 0
    command -> command ++: set output message to matching expenses
    command --> command --:
end
<-- command --:

@enduml