@startuml

hide circle
skinparam classAttributeIconSize 0

package budgetflow.income {
    class Income {
        - category: String
        - amount: double
        - date: String
        + Income(String category, double amount, String date)
        + getCategory(): String
        + getAmount(): double
        + getDate(): String
    }
}

@enduml
