@startuml
hide circle
skinparam classAttributeIconSize 0
    class UI {
        -SCANNER {static}: Scanner
        +showWelcome()
        +readCommand(): String
        +printError(String)
        +printMessage(String)
    }
@enduml