@startuml
''https://plantuml.com/sequence-diagram
skinparam sequenceReferenceBackgroundColor #f7807c
actor User
participant ":Ui" as ui
participant "SCANNER: Scanner" as scanner

create ui
User -> ui ++: readCommand()
ui -> scanner ++: nextLine()
ui <-- scanner --: rawInput: String
ui -> ui ++: trim()
ui --> ui --: trimmedInput()
loop emptyInput
    ref over ui, scanner
        repeat scanning input from user
    end ref
end
User <-- ui --: input: String
@enduml