@startuml
''https://plantuml.com/sequence-diagram
skinparam sequenceReferenceBackgroundColor #f7807c
participant ":FinanceTracker" as FinanceTracker
participant ":Ui" as ui

FinanceTracker -> ui ++: readCommand()
loop empty trimmed Input
    ui -> ui ++: scan next line
    ui --> ui --: scanned input
    ui -> ui ++: trim input
    ui --> ui --: trimmed input
end
FinanceTracker <-- ui --: trimmed input
@enduml